name: Publish Flutter

on:
  pull_request:
    branches:
      - main
    types:
      - closed

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  release:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.version }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'main'

      - name: Check a new tag
        id: tag
        run: |
          export TAG_VERSION=$(grep version pubspec.yaml |  awk -F  ': ' '{print $2}')
          echo "version=$TAG_VERSION" >> $GITHUB_OUTPUT
          echo $TAG_VERSION
          git tag $TAG_VERSION
          git push origin $TAG_VERSION

      - name: Create a Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.version }}

  xcframeworks:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    runs-on: macos-latest
    needs: release
    steps:
      - name: "Checkout TIKI SDK Flutter"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout current tag
        run: |
          git checkout ${{needs.release.outputs.tag}}

      - name: "Setup Flutter"
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.7'

      - name: "Setup XCode"
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: 'Remove unecessary dependencies for native libs'
        run: |
          perl -i -p0e 's/  integration_test:\n    sdk: flutter//s' pubspec.yaml
          perl -i -p0e 's/  path_provider: ^2.0.14//s' pubspec.yaml

      - name: 'Flutter pub get'
        run: |
          flutter pub get

      - name: 'Add embed script in Xcode Project Build phases'
        run: |
          cd .ios
          perl -i -p0e 's/shellScript = "\/bin\/sh \\"\$FLUTTER_ROOT\/packages\/flutter_tools\/bin\/xcode_backend\.sh\\" build";/shellScript = "\/bin\/sh \\"\$FLUTTER_ROOT\/packages\/flutter_tools\/bin\/xcode_backend\.sh\\" build\\n\/bin\/sh \\"\$FLUTTER_ROOT\/packages\/flutter_tools\/bin\/xcode_backend\.sh\\" embed\\n";/s' ./Runner.xcodeproj/project.pbxproj

      - name: "Build Frameworks"
        run: |
          flutter build ios-framework --output=Frameworks --no-profile

      - name: "Zip release frameworks"
        run: |
          cd Frameworks/Release
          zip -r sqlite3.xcframework.zip sqlite3.xcframework
          shasum -a 256 sqlite3.xcframework.zip | cut -f1 -d' '>> sqlite3.xcframework.checksum.txt
          zip -r flutter_secure_storage.xcframework.zip flutter_secure_storage.xcframework
          shasum -a 256 flutter_secure_storage.xcframework.zip | cut -f1 -d' '>> flutter_secure_storage.checksum.txt
          zip -r App.xcframework.zip App.xcframework
          shasum -a 256 App.xcframework.zip | cut -f1 -d' '>> App.checksum.txt
          zip -r Flutter.xcframework.zip Flutter.xcframework
          shasum -a 256 Flutter.xcframework.zip | cut -f1 -d' '>> Flutter.checksum.txt
          zip -r sqlite3_flutter_libs.xcframework.zip sqlite3_flutter_libs.xcframework
          shasum -a 256 sqlite3_flutter_libs.xcframework.zip | cut -f1 -d' '>> sqlite3_flutter_libs.checksum.txt
          zip -r FlutterPluginRegistrant.xcframework.zip FlutterPluginRegistrant.xcframework
          shasum -a 256 FlutterPluginRegistrant.xcframework.zip | cut -f1 -d' '>> FlutterPluginRegistrant.checksum.txt

      - name: "Zip debug frameworks"
        run: |
          cd Frameworks/Debug
          zip -r sqlite3_debug.xcframework.zip sqlite3.xcframework
          shasum -a 256 sqlite3_debug.xcframework.zip | cut -f1 -d' '>> sqlite3.xcframework_debug.checksum.txt
          zip -r flutter_secure_storage_debug.xcframework.zip flutter_secure_storage.xcframework
          shasum -a 256 flutter_secure_storage_debug.xcframework.zip | cut -f1 -d' '>> flutter_secure_storage_debug.checksum.txt
          zip -r App_debug.xcframework.zip App.xcframework
          shasum -a 256 App_debug.xcframework.zip | cut -f1 -d' '>> App_debug.checksum.txt
          zip -r Flutter_debug.xcframework.zip Flutter.xcframework
          shasum -a 256 Flutter_debug.xcframework.zip | cut -f1 -d' '>> Flutter_debug.checksum.txt
          zip -r sqlite3_flutter_libs_debug.xcframework.zip sqlite3_flutter_libs.xcframework
          shasum -a 256 sqlite3_flutter_libs_debug.xcframework.zip | cut -f1 -d' '>> sqlite3_flutter_libs_debug.checksum.txt
          zip -r FlutterPluginRegistrant_debug.xcframework.zip FlutterPluginRegistrant.xcframework
          shasum -a 256 FlutterPluginRegistrant_debug.xcframework.zip | cut -f1 -d' '>> FlutterPluginRegistrant_debug.checksum.txt

      - name: Publish
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Frameworks/Release/*.zip,Frameworks/Release/*.checksum.txt,Frameworks/Debug/*.zip,Frameworks/Debug/*.checksum.txt"
          replacesArtifacts: false
          allowUpdates: true
          tag: ${{needs.release.outputs.tag}}

  aar:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: "Checkout TIKI SDK Flutter"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout current tag
        run: |
          git checkout ${{needs.release.outputs.tag}}

      - name: 'Setup Flutter'
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.7'

      - name: 'Set up Java 11'
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: 'Remove integration_test dependency'
        run: |
          perl -i -p0e 's/  integration_test:\n    sdk: flutter//s' pubspec.yaml

      - name: 'Flutter Pub Get'
        run: |
          flutter pub get

      - name: 'Flutter Build AAR'
        run: |
          flutter build aar

      - name: 'Append publish.gradle script'
        run: |
          cat publish.gradle >> .android/build.gradle

      - name: 'Flutter Build AAR'
        run: |
          flutter build aar --no-debug --no-profile --build-number ${{needs.release.outputs.tag}}
        env:
          GITHUB_USER: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}