name: Test

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.10.5'

      - name: Run Tests
        run: flutter test --reporter github

      - name: Dart Format
        run: |
          cd lib
          dart format . -o show --set-exit-if-changed

      - name: Verify tag version
        id: tag
        run: |
          export export TAG_VERSION=$(grep version pubspec.yaml |  awk -F  ': ' '{print $2}')
          echo "version=$TAG_VERSION" >> $GITHUB_OUTPUT

      - name: Confirm tag version
        run: echo ${{ steps.tag.outputs.version }}
